// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyGvRX3pvIouerakKz43XXNqLYA-7pZNg',
    appId: '1:282811844705:web:3baa1260f8a53fde804220',
    messagingSenderId: '282811844705',
    projectId: 'due-it-16c4a',
    authDomain: 'due-it-16c4a.firebaseapp.com',
    storageBucket: 'due-it-16c4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HiknPoLxk1LpPNKrokzijRBMxcw4N3M',
    appId: '1:282811844705:android:ae83ad58e5338c30804220',
    messagingSenderId: '282811844705',
    projectId: 'due-it-16c4a',
    storageBucket: 'due-it-16c4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbT9hlaqjolvvr6lDIUP8xf_Gtwa_T5pg',
    appId: '1:282811844705:ios:e869db8c7387f476804220',
    messagingSenderId: '282811844705',
    projectId: 'due-it-16c4a',
    storageBucket: 'due-it-16c4a.firebasestorage.app',
    iosBundleId: 'com.example.dueIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbT9hlaqjolvvr6lDIUP8xf_Gtwa_T5pg',
    appId: '1:282811844705:ios:e869db8c7387f476804220',
    messagingSenderId: '282811844705',
    projectId: 'due-it-16c4a',
    storageBucket: 'due-it-16c4a.firebasestorage.app',
    iosBundleId: 'com.example.dueIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyGvRX3pvIouerakKz43XXNqLYA-7pZNg',
    appId: '1:282811844705:web:a79b6053753643ff804220',
    messagingSenderId: '282811844705',
    projectId: 'due-it-16c4a',
    authDomain: 'due-it-16c4a.firebaseapp.com',
    storageBucket: 'due-it-16c4a.firebasestorage.app',
  );
}
